server:
  port: 8096
refreshTokenExpirationDays: 30
accessTokenExpirationDays: 365
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      uri: mongodb://root:root@${MONGODB_HOST:localhost}:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin
      password: root
      database: demo
      port: 27017
      host: ${MONGODB_HOST:localhost}
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true

twilio:
  account_sid: AC6d34d7617d387d7481a2d359a16d9a38
  auth_token: 7a2ca5fb52f9c540a1436071ecb8ceaa
  trial_number: +14067296373